### PR TITLE
Upload progress

### PR DESCRIPTION
**Pull request by bvibber**
Modified Cordova 1.8.1 includes this patch: https://github.com/brion/incubator-cordova-android/commit/c8c1769a65535e2ef1ccf915248ab97ef473ef22

If we set options.params.progress = true, then the success callback gets called during upload progress as well. The progress can be distinguished from the final result because the resultCode is -1.

Only behavior currently is to console.log() it, nothing fancy or visual yet. :)

### CODE REVIEW

**Comment by jdlrobson** [comment]
As discussed on irc this needs a rebase and the javascript needs to adhere to the javascript style guidelines of mediawiki but looks exciting!

**Comment by jdlrobson** [comment]
Is there any way we could also get the total bytes that we are trying to send?
This way it would be possible to do progress bars.

Also
  D/CordovaLog( 8173): Error in success callback: FileTransfer3 = SyntaxError: Unexpected end of input
  D/CordovaLog( 8173): file:///android_asset/www/android/cordova-1.8.1.js: Line 254 : Error in success callback: FileTransfer3 = SyntaxError: Unexpected end of input

**Comment by bvibber** [comment]
Easiest thing to get total bytes is probably to get the file's size before we go sending it... though this might include some outgoing headers as well... in which case it would be nice to have the size of the header _and_ payload. :) That could probably be done, I think it wouldn't be too hard to count up the size of the data-so-far and throw a total into the results object.

Will poke at that tomorrow or so.

**Comment by bvibber** [comment]
Looks like the reported bytes sent does _not_ include HTTP headers, so we can just use the file size safely. Will make a provisional adjustment for that and update.

**Comment by bvibber** [comment]
Jon, how's this look? Hard to test uploads on the plane (no good sample images to use atm and can't use my real phone) but it seems to fetch the right file size. Will clean it up tomorrow.

**Comment by jdlrobson** [comment]
See #38

**Pull request closed without merging**
