### PR TITLE
(bug 39056) Respect system language when loading messages

### PR DESCRIPTION
**Pull request by yuvipanda**
Load messages in the actual system language, do not hard code to english.

### CODE REVIEW

**Comment by bvibber** [comment]
As I recall, it restarts the app but the user-agent string doesn't update... or something horrible like that. :) Needs testing anyway.

**Comment by jdlrobson** [comment]
Add tests...? :-)

**Comment by yuvipanda** [comment]
And ponies? :P

**Comment by yuvipanda** [comment]
So, brion's right - the user agent string doesn't update for a while :( I've updated this to use the Globalization Plugin we're using on Wikipedia app :)

**Comment by jdlrobson** [comment]
We need to write more tests for this sort of thing. Just as a mother tells us to brush our teeth to avoid our teeth looking British we need to write tests so the internet doesn't explode. I am your mother :p

**Comment by yuvipanda** [comment]
Why did I google image search British Teeth? /me scrubs screen with sandpaper

**Comment by yuvipanda** [comment]
@jdlrobson I'm wondering how a test for this would be implemented, since the basic 'problem'/'functionality' was how the app would cope when the language is changed mid-way (Android restarts the app).

/nick TestingNoobie

**Comment by jdlrobson** [comment]
D/CordovaLog( 2958): Uncaught Error: Load timeout for modules: ../android/globalization 
D/CordovaLog( 2958): http://requirejs.org/docs/errors.html#timeout
D/CordovaLog( 2958): file:///android_asset/www/js/require-jquery.js: Line 1635 : Uncaught Error: Load timeout for modules: ../android/globalization 
D/CordovaLog( 2958): http://requirejs.org/docs/errors.html#timeout

Forgot to add a file?

**Comment by yuvipanda** [comment]
Added the missing file.

**Pull request merged**
