### PR TITLE
show loader when loading thumbnails (bug 38936)

### PR DESCRIPTION
**Pull request by jdlrobson**

### CODE REVIEW

**Comment by bvibber** [comment]
Something doesn't seem right here -- I see the spinners all get replaced simultaneously with the X placeholder, and then the X placeholders get replaced with proper images one by one as they load.

**Comment by jdlrobson** [comment]
exploring..

**Comment by jdlrobson** [comment]
fixed. First the loader class was being removed before the src attribute change
Also removing the src attribute before the load prevents a flash of the X placeholder

**Comment by bvibber** [comment]
Awesome. I'll make one more related change so that ImageFetcher doesn't fire the resolve() until we've already loaded a copy of the new image over the network, which will help prevent flashes of empty between the spinner and the loaded image. Merging this for now as it's good to go!

**Pull request merged**
