### PR TITLE
Upgrade to leaflet.js 4.0!

### PR DESCRIPTION
**Pull request by yuvipanda**
leaflet-4.0 was released today, this upgrades to it. Read more at http://leaflet.cloudmade.com/2012/07/30/leaflet-0-4-released.html. 

We should even be able to enable touchZoom on supported devices now (after testing some more)

### CODE REVIEW

**Comment by yuvipanda** [comment]
Sadly, zooming out a few times on my JellyBean Nexus S causes the app to hard crash (segfault) :( Anyone else confirm?

**Comment by yuvipanda** [comment]
Confirmed in stock browser on my phone as well. Can someone on ICS / GB confirm?

**Comment by bvibber** [comment]
No crash zooming out on my Galaxy Nexus (4.0.4) but does crash on my Nexus 7 (4.1.1).

07-30 10:43:42.518: A/libc(21334): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 21347 (WebViewCoreThre)

nooooooooooooooo

**Comment by jdlrobson** [comment]
It doesn't work well with clusters - if you zoom out the clusters stay in place until the zoom out transition has finished and it looks strange.

No crashing on my Galaxy Nexus 4.0.4 or 2.2.2

**Comment by yuvipanda** [comment]
We possibly need to update our clusterer plugin too for the clustering weirdness.

**Comment by bvibber** [comment]
Probably the cluster items need to be placed in an appropriate container for them to get translated along with the other zoomy animations...

**Comment by jdlrobson** [comment]
This is sexy:
https://github.com/danzel/Leaflet.markercluster

**Comment by jdlrobson** [comment]
Replaced by #239 which addresses clustering problem

**Pull request closed without merging**
