### PR TITLE
My uploads

### PR DESCRIPTION
**Pull request by yuvipanda**
My uploads for completed uploads.

Uses WebSQL for storage. Can be easily extended to handle incomplete uploads too.

Notes:
- Should probably create a 'Photo' prototype that should abstract away a lot of this code
- UI polish needed on the completed upload photo page - perhaps should be the same as the screen you take people to after their photo is successfully uploaded

### CODE REVIEW

**Comment by jdlrobson** [comment]
This pull request breaks the test suite. Please run assets/www/test.html and resolve.

**Comment by jdlrobson** [comment]
- We should show a message where there are no uploads - I'm seeing lots of blank screens
- Should add link from upload success page to my uploads
- Would it not be better to use the api to request uploads rather than caching uploads? If I use multiple devices it would be good to see uploads across devices rather than on a specific device

**Comment by jdlrobson** [comment]
Also it seems strange that if I upload an image in Switzerland I would not expect it to appear in the my uploads tab when viewing monuments in Austria - we should either only show uploads that match with one of the monuments in the monuments list.

**Comment by yuvipanda** [comment]
As per discussion on IRC, I think moving it out of a tab elsewhere should fix the last comment

**Comment by yuvipanda** [comment]
Updated to not break tests. Also updated to not fail when user enters wrong password once. Shows no-uploads message when there are no uploads.

I'm refactoring a bunch of things into a Photo object in another commit, so linking to this from the 'upload-done' page would be easier. I think merging this in now would be a good idea :D

**Pull request merged**
