### PR TITLE
ignore @yuvipanda whitelist (bug 39568)

### PR DESCRIPTION
**Pull request by jdlrobson**
this enables various campaigns including serbia

### CODE REVIEW

**Comment by awjrichards-zz** [comment]
When viewing a monument, beneath the monument's photo now reads:
'Campaign: undefined'

Otherwise, data associated with the photo upload itself still looks good:
http://test.wikipedia.org/wiki/File:Casa_Balletb%C3%B3_(Sant_Juli%C3%A0_de_L%C3%B2ria)_(taken_on_22Aug2012_16hrs58mins44secs).jpg

If we can figure out what to do about the 'Campaign: undefined' problem, I think this solution is good.

**Comment by jdlrobson** [comment]
Good spot! once #168 is merged we can borrow the trick there.

**Comment by bvibber** [comment]
Now instead of "Campaign: undefined" I just see "Campaign:" -- it's still not listing any actual name. :(

**Comment by jdlrobson** [comment]
fixed. Now just showing the top level campaign.

**Comment by awjrichards-zz** [comment]
I actually think that is misleading, as the 'top level campaign' you're using is not a campaign. It's some regional subdivision. Without having the actual campaign names available, we have no reliable human-readable way to discern the specific campaign a monument belongs to. Probably either the 'Campaign:' line should go away completely, or we'll have to think of something else. That something else could be that we (at least for now) maintain a white-list of campaign names in the repository itself so it's trivial to amend (similar to what Yuvi had done, but in a slightly more obvious/visible way than some random wiki page). I'll bring it up with Phil - we should try to get this done for today's beta, otherwise it's going to be difficult to thoroughly test the app in SF :p

**Comment by awjrichards-zz** [comment]
For now I've just whitelisted the missing campaigns so we don't have to block on this change, which I think needs some more thought. Updated campaign data: https://github.com/wikimedia/WLMMobile/pull/180

**Comment by yuvipanda** [comment]
Yay to killing random hacks!

**Comment by awjrichards-zz** [comment]
Closing this request as the issue was resolved in https://github.com/wikimedia/WLMMobile/pull/208

**Pull request closed without merging**
